# Generated by Django 5.2.1 on 2025-05-20 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_matricule', models.CharField(max_length=20, unique=True)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('specialite', models.CharField(max_length=100)),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('coefficient', models.IntegerField(default=1)),
                ('classes', models.ManyToManyField(to='base.classe')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')])),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('date_generation', models.DateField(default=django.utils.timezone.now)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'trimestre', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now)),
                ('type_evaluation', models.CharField(default='Examen', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')], default=1)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.matiere')),
            ],
            options={
                'unique_together': {('etudiant', 'matiere', 'trimestre', 'type_evaluation')},
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')])),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('date_generation', models.DateField(default=django.utils.timezone.now)),
                ('moyenne_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meilleure_note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moins_bonne_note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classe')),
            ],
            options={
                'unique_together': {('classe', 'trimestre', 'annee_scolaire')},
            },
        ),
    ]
