# Generated by Django 5.2 on 2025-05-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_absence_id_alter_bulletin_id_alter_classe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.CharField(choices=[('IIR', 'Ingénierie Informatique & Réseaux'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GCBTP', 'Génie Civil, Bâtiments et Travaux Publics'), ('GI', 'Génie Industriel'), ('GF', 'Génie Financier')], default='IIR', max_length=10),
        ),
    ]
