# Generated by Django 5.2 on 2025-05-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_classe_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professeur',
            name='niveaux_enseignes',
            field=models.CharField(default='1,2,3,4,5', help_text='Niveaux séparés par des virgules (ex: 1,3,5)', max_length=20),
        ),
    ]
