# Generated by Django 5.2 on 2025-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cours_niveau_professeur_niveaux_enseignes'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.IntegerField(default=1, help_text="Niveau d'ingénieur (1 à 5)"),
        ),
    ]
