# Generated by Django 5.2 on 2025-05-27 00:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_etudiant_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(default=base.models.get_current_date),
        ),
    ]
