# Generated by Django 5.2 on 2025-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_etudiant_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='filieres',
            field=models.CharField(blank=True, help_text='Filières séparées par des virgules (ex: IIR,GESI)', max_length=255),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
